- id: mirror-check
  name: mirror check
  language: python
  entry: mirror -q check
  args: [--pre-commit]
  always_run: true
  pass_filenames: false
  require_serial: true
  description: Mirror|rorriM
